---
repos:
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v4.5.0
  #   hooks:
  #     - id: trailing-whitespace
  #     - id: check-added-large-files
  #     - id: check-yaml
  #     - id: fix-byte-order-marker
  #     - id: end-of-file-fixer
  #     - id: mixed-line-ending

  # - repo: https://github.com/DavidAnson/markdownlint-cli2
  #   rev: v0.12.1
  #   hooks:
  #   - id: markdownlint-cli2

  - repo: local
    hooks:
      - id: check_categories-list
        name: check_categories-list
        entry: .hooks/check_categories-list.sh
        language: script
        pass_filenames: false
      - id: check_post-directory-name
        name: check_post-directory-name
        entry: .hooks/check_post-directory-name.sh
        language: script
        pass_filenames: false
      - id: check_post-filename
        name: check_post-filename
        entry: .hooks/check_post-filename.sh
        language: script
        pass_filenames: false
      - id: check_post-headers
        name: check_post-headers
        entry: .hooks/check_post-headers.sh
        language: script
        pass_filenames: false
